pairlegal-documentation/docs/external_information.md, pairlegal-documentation/i18n/cs/docusaurus-plugin-content-docs/current/external_information.md, pairlegal-documentation/i18n/de/docusaurus-plugin-content-docs/current/external_information.md
=> feat: update external content

pairlegal-documentation/docs/AI.md, pairlegal-documentation/docs/alerts.md, pairlegal-documentation/docs/definition-extraction.md, pairlegal-documentation/docs/editing.md, pairlegal-documentation/docs/security.md, pairlegal-documentation/i18n/cs/docusaurus-plugin-content-docs/current/AI.md, pairlegal-documentation/i18n/cs/docusaurus-plugin-content-docs/current/alerts.md, pairlegal-documentation/i18n/cs/docusaurus-plugin-content-docs/current/definition-extraction.md, pairlegal-documentation/i18n/cs/docusaurus-plugin-content-docs/current/editing.md, pairlegal-documentation/i18n/cs/docusaurus-plugin-content-docs/current/security.md, pairlegal-documentation/i18n/de/docusaurus-plugin-content-docs/current/AI.md, pairlegal-documentation/i18n/de/docusaurus-plugin-content-docs/current/alerts.md, pairlegal-documentation/i18n/de/docusaurus-plugin-content-docs/current/authentication.md, pairlegal-documentation/i18n/de/docusaurus-plugin-content-docs/current/definition-extraction.md, pairlegal-documentation/i18n/de/docusaurus-plugin-content-docs/current/editing.md, pairlegal-documentation/i18n/de/docusaurus-plugin-content-docs/current/security.md
- **feat: expand content**
- **editing video**
=> feat: expand content: ai, editing

pairlegal-documentation/docs/installation/index.mdx, pairlegal-documentation/i18n/de/docusaurus-plugin-content-docs/current/AI.md, pairlegal-documentation/i18n/de/docusaurus-plugin-content-docs/current/alerts.md, pairlegal-documentation/i18n/de/docusaurus-plugin-content-docs/current/definition-extraction.md, pairlegal-documentation/i18n/de/docusaurus-plugin-content-docs/current/external_information.md, pairlegal-documentation/i18n/de/docusaurus-plugin-content-docs/current/getting_started.md, pairlegal-documentation/i18n/de/docusaurus-plugin-content-docs/current/installation/install365.mdx, pairlegal-documentation/i18n/de/docusaurus-plugin-content-docs/current/installation/troubleshooting.mdx
=> chore: german translation

pairlegal-documentation/docs/editing.md, pairlegal-documentation/i18n/cs/docusaurus-plugin-content-docs/current/editing.md, pairlegal-documentation/i18n/de/docusaurus-plugin-content-docs/current/editing.md
=> feat: specify rewrite

pairlegal-documentation/i18n/cs/docusaurus-plugin-content-docs/current/editing.md
=> chore: minor cs improvements

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/epic.yml, .github/ISSUE_TEMPLATE/feature-request.yml, .github/ISSUE_TEMPLATE/other.yml
=> chore: issue templ

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/epic.yml, .github/ISSUE_TEMPLATE/feature-request.yml
=> fix: do not require templates

pairlegal-documentation/docs/subscription.mdx
=> feat: team admin onboarding

pairlegal-documentation/docs/subscription.mdx
=> feat: purchaser auto added to sub

pairlegal-documentation/docs/editing/integrations.md
=> feat: improve docs

pairlegal-documentation/docs/editing/integrations.md
=> feat: slight rewording

pairlegal-documentation/docs/AI.md
=> feat: refresh ai page

.github/dependabot.yml
=> chore: react deps group

pairlegal-documentation/docs/features/external_information.mdx
=> chore: upper i

pairlegal-documentation/docs/features/AI.mdx, pairlegal-documentation/docs/features/definition-extraction.mdx, pairlegal-documentation/docs/getting_started.md, pairlegal-documentation/docs/installation/authentication.mdx, pairlegal-documentation/docs/installation/index.mdx, pairlegal-documentation/docs/installation/troubleshooting.mdx, pairlegal-documentation/docs/settings/external_services.mdx, pairlegal-documentation/docs/settings/user_management/index.mdx, pairlegal-documentation/docs/use_cases/ai_customization.md, pairlegal-documentation/docs/use_cases/error_prevention.md, pairlegal-documentation/docs/use_cases/fast_drafting.md, pairlegal-documentation/docs/use_cases/index.mdx, pairlegal-documentation/docs/use_cases/knowledge_reuse.md
- **feat: add use cases**
- **chore: videos**
- **feat: snippets video**
=> feat: add use cases section

pairlegal-documentation/docs/features/snippets.mdx, pairlegal-documentation/docs/use_cases/ai_customization.md, pairlegal-documentation/docs/use_cases/fast_drafting.md, pairlegal-documentation/docs/use_cases/knowledge_reuse.md
=> feat: minor changes

pairlegal-documentation/docs/use_cases/error_prevention.md, pairlegal-documentation/docs/use_cases/fast_drafting.md
=> fix: switch video

pairlegal-documentation/docs/use_cases/error_prevention.md, pairlegal-documentation/docs/use_cases/fast_drafting.md
=> feat: add upcoming features

pairlegal-documentation/docs/installation/enterprise.mdx
=> fix: broken link

pairlegal-documentation/docs/installation/enterprise.mdx, pairlegal-documentation/docusaurus.config.js
=> fix: link xml

pairlegal-documentation/docs/installation/enterprise.mdx
=> fix: link attempt 4

pairlegal-documentation/docs/settings/external_services.mdx, pairlegal-documentation/docusaurus.config.js
=> fix: change team admin link, disable blog indexing
